### ISSUE TITLE
New release with `allow_nil`

### ISSUE THREAD

**Issue by hugopeixoto** [ankane/str_enum#1]
Hi, there!

Would it be possible to make a new release with this new feature included?

**Comment by ankane** [comment]
Hey @hugopeixoto, what's the reason for the request? Are you trying to release a gem that depends on it?

**Comment by hugopeixoto** [comment]
Hi @ankane :) It's mostly to avoid having to pin it to a specific commit, in case any other commits land on `master`.

Since it's been a while since the feature was implemented, I thought it might be nice to release it.

**Comment by ankane** [comment]
Bundler was designed to handle this case, so not sure it's enough of a reason to do a release.
