### ISSUE TITLE
str_enum columns are included on `.select`

### ISSUE THREAD

**Issue by darwintantuco** [ankane/str_enum#11]
Steps to reproduce:
1. Create users table and add firstname, lastname and status columns
2. Use str_enum on status column (`str_enum :status, [:active, :archived]`)
3. Create few records on users table
4. On rails console, run: `User.all.select(:firstname)`

I would expect status column to not be included but it seems str_enum columns are always included when you use `.select`, not sure if this is expected

![Screen Shot 2023-11-26 at 11 07 58](https://github.com/ankane/str_enum/assets/15992303/e81feec0-ad81-4d43-ad6b-05ebda326f5c)

**Comment by ankane** [comment]
Hi @darwintantuco, thanks for reporting! Fixed in the commit above.
