### ISSUE TITLE
Implementing write accessors

### ISSUE THREAD

**Issue by cknoxrun** [ankane/str_enum#2]
Any thoughts on adding the bang write accessors similar to ActiveRecord::Enum?

```
conversation.active!
```

which would essentially be equivalent to

```
conversation.status = "active"
conversation.save!
```

Let me know what you think and I can put together a pull request.

**Comment by ankane** [comment]
Hey @cknoxrun, sounds good to me 👍

**Comment by ankane** [comment]
Cleaning up issues. Feel free to submit a PR if you're still interested.
