### ISSUE TITLE
Feature request: mimic Rails' 6 negative scopes

### ISSUE THREAD

**Issue by swiknaba** [ankane/str_enum#4]
Rails 6 added negative scopes, would you consider adding these to str_enum as well?

See related Pull Request https://github.com/rails/rails/pull/35381:

> ```ruby
> class Post < ActiveRecord::Base
>  enum status: %i[ drafted active trashed ]
>end
> ```

>Post.not_drafted # => where.not(status: :drafted)
>Post.not_active  # => where.not(status: :active)
>Post.not_trashed # => where.not(status: :trashed)
>Particularly convenient when you want to disallow access in a controller, like Post.not_trashed.find(params[:id]).

**Comment by ankane** [comment]
Hey @swiknaba, nice find. Added on master.
