### ISSUE TITLE
Ability to specify validation message?

### ISSUE THREAD

**Issue by gregblass** [ankane/str_enum#5]
Hey there! I was wondering if there is a way to specify the validation messaging. 'is not included in the list' doesn't quite fit the standard messaging for other fields in Rails.

In other words - all my other fields have validation messaging like "can't be blank" - but because one of the fields on the model is a str_enum, it has different messaging, which isn't quite a uniform experience to the user.

Is this possible?

![image](https://user-images.githubusercontent.com/279927/66662790-77cf7b80-ec17-11e9-8f36-37101b82d944.png)

**Comment by gregblass** [comment]
It's weird...looking through the source code...I don't even see any case where you are specifying that language. So then it must actually be a rails thing?

**Comment by gregblass** [comment]
I see where it's happening - right here: https://github.com/ankane/str_enum/blob/b2427e7c1279e16fea4949859c24eb8347a16efd/lib/str_enum/model.rb#L11

I wonder if its possible to pass in something to override that?

**Comment by ankane** [comment]
Hey @gregblass, agree it makes more sense for the presence validation message to come before the inclusion message. Just pushed the change to master. Can you give it a shot?

**Comment by ankane** [comment]
Closing due to no response

**Comment by gregblass** [comment]
Hey I’m so sorry, I could have sworn I responded here. Thank you so much man - I’ll give it a shot today!

**Comment by ankane** [comment]
No worries, released 0.2.0 with the change.
