### ISSUE TITLE
Question: metadata?

### ISSUE THREAD

**Issue by seanfcarroll** [ankane/str_enum#8]
Howdy, I'm building a generator and I'd love to be able to query a model or model instance and see if there is a str_enum attached to a column and return the name of the str_enum.

Any ideas how I might do that?

**Comment by ankane** [comment]
Hey @seanfcarroll, the gem doesn't keep track of metadata, but you could use `Module#prepend` with a `str_enum` method to capture it.

**Comment by seanfcarroll** [comment]
Thanks @ankane, I'm not clear how to use `Module#prepend` to solve this problem, but it is really a SO problem, so I asked it [over there](https://stackoverflow.com/questions/65331528/using-moduleprepend-to-interrogate-a-str-enum).

Cheers!
